AdminLoginCode/Controllers/CoursesToViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AdminLoginCode.Controllers
{
    public class CoursesToViewController : Controller
    {
        public FinalCaseStudyEntities db = new FinalCaseStudyEntities();
        // GET: CoursesToView


        public ActionResult Index()
        {
            var Course = db.CourseDetails.ToList();
            return View(Course);

        }

        // GET: CourseDetails/Details/5
        public ActionResult Search()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Search(string Course_Name)
        {
            var Courses = db.CourseDetails.Where(b => b.Course_Name == Course_Name).ToList();

            if (Courses == null || !Courses.Any())
            {
                ViewBag.Message = "No flights found between " + Course_Name;
            }
            return View("Index", Courses);
        }
        


    }

}

AdminLoginCode/Views/CoursesToView/Details.cshtml
@model IEnumerable<AdminLoginCode.Controllers.CourseDetail>

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Course_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course_Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course_Fee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacultyName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Course_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course_Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course_Fee)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FacultyName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Course_Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Course_Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Course_Id })
        </td>
    </tr>
}

</table>

AdminLoginCode/Views/CoursesToView/Index.cshtml
@*@model WebApplication1.Controllers.FlightManagement*@
@model IEnumerable<AdminLoginCode.Controllers.CourseDetail>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Search For Courses</h2>

<form method="post" action="@Url.Action("Search", "CoursesToView")">
    <div>
        <label>Select the Course</label>
        <input type="text" name="Course_Name" placeholder="Enter Course" required />
    </div>
    @*<div>
        <label>To:</label>
        <input type="text" name="destination" placeholder="Enter destination city" required />
    </div>*@
    <div>
        <button type="submit">Search</button>
    </div>
</form>

@*@if (Model != null && Model.Any())*@

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr >
                <th>CourseID</th>
                <th>CourseName</th>
                <th>CourseDescription</th>
                <th>Course Fee</th>
                <th>Faculty Name</th>
                
                @* <th></th>*@
            </tr>
        </thead>
        <tbody>
            @foreach (var CourseDetail in Model)
            {
                <tr>
                    <td>@CourseDetail.Course_Id</td>
                    <td>@CourseDetail.Course_Name</td>
                    <td>@CourseDetail.Course_Fee</td>
                    <td>@CourseDetail.FacultyName</td>
                    <td>@CourseDetail.Course_Description</td>
                    

                </tr>
            }
        </tbody>
    </table>
}
<style>
    body {
        background-image: url('../../images/std3.jpg');

    }
    .table {
        width: 100%;
        border-collapse: collapse;
        font-family: Arial, sans-serif;
        margin: 20px 0;
    }

        .table th, .table td {
            border: 1px solid #ccc;
            padding: 12px;
            text-align: left;
        }

        .table th {
            background-color: #4CAF50;
            color: white;
            font-weight: bold;
        }

        .table tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .table tr:hover {
            background-color: #f1f1f1;
        }

        .table td {
            transition: background-color 0.3s;
        }

            .table td:hover {
                background-color: #eaeaea;
            }
</style>

AdminLoginCode/Views/CoursesToView/Search.cshtml
@*
@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>
*@
@model IEnumerable<AdminLoginCode.Controllers.CourseDetail>
@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<form method="post" action="@Url.Action("Search", "Courses")">

    <div>
        <label>Select the Course:</label>
        <input type="text" name="Course_Name" placeholder="Enter Course" required />
    </div>
    @*<div>
            <label>To:</label>
            <input type="text" name="destination" placeholder="Enter destination city" required />
        </div>*@
    <div>
        <button type="submit">Course_Name</button>
    </div>
</form>

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>CourseID</th>
                <th>CourseName</th>
                <th>CourseDescription</th>
                <th>Course Fee</th>
                <th>Faculty Name</th>

                @* <th></th>*@
            </tr>
        </thead>
        <tbody>
            @foreach (var CourseDetail in Model)
            {
                <tr>
                    <td>@CourseDetail.Course_Id</td>
                    <td>@CourseDetail.Course_Name</td>
                    <td>@CourseDetail.Course_Fee</td>
                    <td>@CourseDetail.FacultyName</td>
                    <td>@CourseDetail.Course_Description</td>


                </tr>
            }
        </tbody>
    </table>
}