AdminLoginCode/Controllers/StudentstoEnrollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminLoginCode.Controllers
{
    public class StudentstoEnrollController : Controller
    {
        public FinalCaseStudyEntities db = new FinalCaseStudyEntities();
            // GET: CoursesToView
            public ActionResult Index()
            {
                var Course = db.CourseDetails.ToList();
                return View(Course);

            }

            // GET: CourseDetails/Details/5
            public ActionResult Search()
            {
                return View();
            }
            [HttpPost]
            public ActionResult Search(int StudentId)
            {
                var Courses = db.StudentDetails.Where(b => b.StudentId == StudentId).ToList();

                if (Courses == null || !Courses.Any())
                {
                    ViewBag.Message = "No Id Found " + StudentId;
                }
                return View("Index", Courses);
            }

            // GET: StudentstoEnroll
        
    }
}

AdminLoginCode/Views/StudentstoEnroll/Index.cshtml
@model IEnumerable<AdminLoginCode.Controllers.StudentDetail>

@{
    ViewBag.Title = "Index";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StudentId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateofBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CollegeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HallTicketNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GuardianName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GuardianContactNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contact)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StudentId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)

        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StudentName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateofBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CollegeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HallTicketNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GuardianName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GuardianContactNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Contact)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>

        <a href="/StudentstoEnroll/Search" class="btn btn-info">Back</a>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.StudentId }) |
            @Html.ActionLink("Details", "Details", new { id=item.StudentId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.StudentId })
        </td>*@
    </tr>
}

</table>

<style>
    body {
        background-image: url('../../images/sucess.png');
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        height: 100vh;
    }
</style>

AdminLoginCode/Views/StudentstoEnroll/Search.cshtml
@*@model AdminLoginCode.Controllers.StudentDetail*@
@model IEnumerable<AdminLoginCode.Controllers.StudentDetail>

@{
    ViewBag.Title = "Search";
}
@*@model IEnumerable<AdminLoginCode.Controllers.CourseDetail>

    @{
        ViewBag.Title = "Index";
    }*@
<h2>Search For  Student Enrolled</h2>

<form method="post" action="@Url.Action("Search", "StudentstoEnroll")">
    <div>
        <label>StudentId</label>
        <input type="text" name="StudentId" placeholder="StudentId" required />
    </div>
    @*<div>
            <label>To:</label>
            <input type="text" name="destination" placeholder="Enter destination city" required />
        </div>*@
    <div>
        <button type="submit">Search</button>
    </div>
</form>

@*@if (Model != null && Model.Any())*@

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>StudentId</th>
                <th>StudentName</th>
                <th>FirstName</th>
                <th>LastName </th>
                <th>Email</th>
                <th>DateofBirth</th>
                <th>Gender</th>
                <th>CollegeName</th>
                <th>HallTicketNumber </th>
                <th>GuardianName</th>
                <th>GuardianContactNumber</th>
                <th>Contact</th>
                <th>Address</th>
                @* <th></th>*@
            </tr>
        </thead>
        <tbody>
            @foreach (var CourseDetail in Model)
            {
                <tr>
                    <td>StudentId</td>
                    <td>StudentName</td>
                    <td>FirstName</td>
                    <td>LastName </td>
                    <td>Email</td>
                    <td>DateofBirth</td>
                    <td>Gender</td>
                    <td>CollegeName</td>
                    <td>HallTicketNumber </td>
                    <td>GuardianName</td>
                    <td>GuardianContactNumber</td>
                    <td>Contact</td>
                    <td>Address</td>

                </tr>
            }
        </tbody>
    </table>
}
<style>
    body {
        background-image: url('../../images/greenbackground.png');
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        height: 100vh;
    }
</style>